# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
      - bash: echo Build First Job
  - job: SecondJob
    steps:
      - bash: echo Build Second Job 
      - bash: echo ${PipelineLevelVariable}
- stage: DevDeploy
  variables:
   environment: Dev 
  jobs:
  - job: DevDeployJob
    steps:
      - bash: echo ${environment}DeployJob 
  dependsOn: Build
 
- stage: QADeploy
  variables:
   environment: QA 
  jobs:
  - job: QADeployJob
    steps:
      - bash: echo ${environment}DeployJob 
  dependsOn: Build

- stage: ProdDeploy
  variables:
   environment: PROD
  jobs:
  - job: ProdDeployJob
    steps:
      - bash: echo ${environment}DeployJob 
  dependsOn: 
  - Build
  - QADeploy
  - DevDeploy



